### ISSUE TITLE
packaged apps require icons property in manifest.webapp

### ISSUE THREAD

**Issue by mykmelez** [mozilla/r2d2b2g#311]
When I try to add a packaged app that doesn't specify the _icons_ property in its manifest, the Simulator throws an exception and fails to add the app:

```
error: r2d2b2g: An exception occurred.
TypeError: webapp.icons is not an object
resource://r2d2b2g-at-mozilla-dot-org/r2d2b2g/lib/simulator.js 111
Traceback (most recent call last):
  File "resource://r2d2b2g-at-mozilla-dot-org/addon-sdk/lib/sdk/timers.js", line 31, in notify
    callback.apply(null, args);
  File "resource://r2d2b2g-at-mozilla-dot-org/addon-sdk/lib/sdk/content/worker.js", line 111, in onContentEvent/<
    self._emit.apply(self, JSON.parse(args));
  File "resource://r2d2b2g-at-mozilla-dot-org/addon-sdk/lib/sdk/deprecated/events.js", line 123, in _emit
    return this._emitOnObject.apply(this, args);
  File "resource://r2d2b2g-at-mozilla-dot-org/addon-sdk/lib/sdk/deprecated/events.js", line 153, in _emitOnObject
    listener.apply(targetObj, params);
  File "resource://r2d2b2g-at-mozilla-dot-org/addon-sdk/lib/sdk/content/worker.js", line 223, in postMessage
    self._addonWorker._emit('message', data);
  File "resource://r2d2b2g-at-mozilla-dot-org/addon-sdk/lib/sdk/deprecated/events.js", line 123, in _emit
    return this._emitOnObject.apply(this, args);
  File "resource://r2d2b2g-at-mozilla-dot-org/addon-sdk/lib/sdk/deprecated/events.js", line 153, in _emitOnObject
    listener.apply(targetObj, params);
  File "resource://r2d2b2g-at-mozilla-dot-org/r2d2b2g/lib/simulator.js", line 737, in onMessage
    simulator.addAppByDirectory();
  File "resource://r2d2b2g-at-mozilla-dot-org/r2d2b2g/lib/simulator.js", line 111, in module.exports.addAppByDirectory
    let size = Object.keys(webapp.icons).sort(function(a, b) b - a)[0] || null;
```

The _icons_ property is optional, so the Simulator shouldn't assume it will be present.

**Comment by nickdesaulniers** [comment]
VERIFIED FIXED
