### ISSUE TITLE
tests think device isn't connected or fail w/"Device not connected"

### ISSUE THREAD

**Issue by mykmelez** [mozilla/r2d2b2g#779]
I'm seeing strange test ADB behavior with a device connected.  The test script sees the connected device but then decides that it isn't connected, so it skips the connected device tests:

```
info: r2d2b2g: executing 'r2d2b2g/tests/test-main.test ab list devices'
info: r2d2b2g: onTrackReady
info: r2d2b2g: pass: Devices: [["full_unagi","device"]]
info: r2d2b2g: Device is not plugged in
info: r2d2b2g: executing 'r2d2b2g/tests/test-main.test b adb.shell, no phone'
info: r2d2b2g: pass: undefined
info: r2d2b2g: executing 'r2d2b2g/tests/test-main.test c adb push, no phone'
info: r2d2b2g: pass: undefined
info: r2d2b2g: executing 'r2d2b2g/tests/test-main.test d adb shell, with phone'
info: r2d2b2g: pass: Skipping test
info: r2d2b2g: executing 'r2d2b2g/tests/test-main.test e adb push, with phone'
info: r2d2b2g: pass: Skipping test
info: r2d2b2g: executing 'r2d2b2g/tests/test-main.test zz after'
```

After looking at the code, the fix seemed pretty obvious:

```
diff --git a/addon/test/test-main.js b/addon/test/test-main.js
index fedd954..18f5e68 100644
--- a/addon/test/test-main.js
+++ b/addon/test/test-main.js
@@ -97,16 +97,18 @@ exports = (function(exports) {
         function success(e) {
           if (ADB.didRunInitially && e[0]) {
             let [, status] = e[0];
             if (status === "offline") {
               isPhonePluggedIn = false;
               assert.fail("Device is offline");
               done();
               return;
+            } else {
+              isPhonePluggedIn = true;
             }
           } else {
             // adb-fallback returns a string if the device is plugged in
             isPhonePluggedIn = !!e[0];
           }

           if (isPhonePluggedIn) {
             assert.pass("Devices: " + JSON.stringify(e));
```

And that does fix the problem; but it exposes test failures:

```
info: r2d2b2g: executing 'r2d2b2g/tests/test-main.test ab list devices'
TCPSocket: content process: false

TCPSocket: window init: undefined
TCPSocket: startup called

TCPSocket: Host info: 127.0.0.1:5037

TCPSocket: SSL: false

info: r2d2b2g: onTrackReady
info: r2d2b2g: pass: Devices: [["full_unagi","device"]]
info: r2d2b2g: Device is plugged in
info: r2d2b2g: executing 'r2d2b2g/tests/test-main.test b adb.shell, no phone'
info: r2d2b2g: pass: Skipping test
info: r2d2b2g: executing 'r2d2b2g/tests/test-main.test c adb push, no phone'
info: r2d2b2g: pass: Skipping test
info: r2d2b2g: executing 'r2d2b2g/tests/test-main.test d adb shell, with phone'
info: r2d2b2g: Running adb shell
error: r2d2b2g: fail: Shell failed: "Device not connected"
info: r2d2b2g: Traceback (most recent call last):
  File "resource://gre/modules/commonjs/sdk/timers.js", line 31, in notify
    callback.apply(null, args);
  File "resource://gre/modules/commonjs/sdk/deprecated/unit-test.js", line 288, in null
    timer.setTimeout(function() { onDone(self); }, 0);
  File "resource://gre/modules/commonjs/sdk/deprecated/unit-test.js", line 458, in null
    options.onDone(self);
  File "resource://gre/modules/commonjs/sdk/deprecated/unit-test.js", line 440, in runNextTest
    self.start({test: test, onDone: runNextTest});
  File "resource://gre/modules/commonjs/sdk/deprecated/unit-test.js", line 471, in start
    this.test.testFunction(this);
  File "resource://gre/modules/commonjs/sdk/test.js", line 64, in null
    test(assert, function() {
  File "resource://r2d2b2g-at-mozilla-dot-org/r2d2b2g/tests/test-main.js", line 185, in exports["test d adb shell, with phone"]
    function fail(e) {
  File "resource://gre/modules/commonjs/sdk/core/promise.js", line 155, in then
    result.then(resolve, reject);
  File "resource://gre/modules/commonjs/sdk/core/promise.js", line 54, in then
    return { then: function then(fulfill, reject) { reject(reason); } };
  File "resource://gre/modules/commonjs/sdk/core/promise.js", line 135, in reject
    if (onError) deferred.resolve(onError(reason));
  File "resource://r2d2b2g-at-mozilla-dot-org/r2d2b2g/tests/test-main.js", line 186, in fail
    assert.fail("Shell failed: " + JSON.stringify(e));
  File "resource://gre/modules/commonjs/sdk/test/assert.js", line 74, in fail
    this._log.fail(e);
  File "resource://gre/modules/commonjs/sdk/deprecated/unit-test.js", line 88, in fail
    this.console.trace();
  File "resource://gre/modules/commonjs/sdk/lang/functional.js", line 71, in null
    return function() fn.apply(this, args.concat(Array.slice(arguments)));
info: r2d2b2g: executing 'r2d2b2g/tests/test-main.test e adb push, with phone'
error: r2d2b2g: fail: Error pushing: Device not connected
info: r2d2b2g: Traceback (most recent call last):
  File "resource://gre/modules/commonjs/sdk/timers.js", line 31, in notify
    callback.apply(null, args);
  File "resource://gre/modules/commonjs/sdk/deprecated/unit-test.js", line 288, in null
    timer.setTimeout(function() { onDone(self); }, 0);
  File "resource://gre/modules/commonjs/sdk/deprecated/unit-test.js", line 458, in null
    options.onDone(self);
  File "resource://gre/modules/commonjs/sdk/deprecated/unit-test.js", line 440, in runNextTest
    self.start({test: test, onDone: runNextTest});
  File "resource://gre/modules/commonjs/sdk/deprecated/unit-test.js", line 471, in start
    this.test.testFunction(this);
  File "resource://gre/modules/commonjs/sdk/test.js", line 64, in null
    test(assert, function() {
  File "resource://r2d2b2g-at-mozilla-dot-org/r2d2b2g/tests/test-main.js", line 215, in exports["test e adb push, with phone"]
    function fail(e) {
  File "resource://gre/modules/commonjs/sdk/core/promise.js", line 155, in then
    result.then(resolve, reject);
  File "resource://gre/modules/commonjs/sdk/core/promise.js", line 54, in then
    return { then: function then(fulfill, reject) { reject(reason); } };
  File "resource://gre/modules/commonjs/sdk/core/promise.js", line 135, in reject
    if (onError) deferred.resolve(onError(reason));
  File "resource://r2d2b2g-at-mozilla-dot-org/r2d2b2g/tests/test-main.js", line 216, in fail
    assert.fail("Error pushing: " + e);
  File "resource://gre/modules/commonjs/sdk/test/assert.js", line 74, in fail
    this._log.fail(e);
  File "resource://gre/modules/commonjs/sdk/deprecated/unit-test.js", line 88, in fail
    this.console.trace();
  File "resource://gre/modules/commonjs/sdk/lang/functional.js", line 71, in null
    return function() fn.apply(this, args.concat(Array.slice(arguments)));
info: r2d2b2g: executing 'r2d2b2g/tests/test-main.test zz after'
info: r2d2b2g: Closing ADB
info: r2d2b2g: ADB closed in 4ms
```

cc: @bkase

**Comment by mykmelez** [comment]
After the most recent round of fixes, I can no longer reproduce!
